<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcVhOFy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcVhOFy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXcVhOFy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXcVhOFy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXcVhOFy\App_KernelDevDebugContainer([
    'container.build_hash' => 'XcVhOFy',
    'container.build_id' => '080b82eb',
    'container.build_time' => 1699631008,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcVhOFy');
